version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chess-admin-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-please-change-me}
      - DB_PATH=/app/data/chess-club.db
    volumes:
      - chessclub_data:/app/data
    ports:
      - "4000:4000"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chess-admin-web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - NGINX_PORT=80
    ports:
      - "5173:80"

volumes:
  chessclub_data:
